name: 'COVID_19'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

models:
  COVID_19:
    staging:
      +materialized: view
      +schema: bronze

    intermediate:
      +materialized: table
      +schema: silver

    dimensions:
      +materialized: table
      +schema: gold

    facts:
      +materialized: incremental
      +schema: gold