version: 2

sources:
  - name: bronze_source
    database: COVID_2021
    schema: BRONZE
    tables:
      - name: RAW_LEITO_OCUPACAO_2021
      - name: RAW_MUNICIPIOS_IBGE
      - name: RAW_ESTABELECIMENTOS_CNES

models:
  - name: dim_tempo
    description: "Dimensão temporal com informações detalhadas sobre datas"
    columns:
      - name: id_tempo
        description: "Chave primária da dimensão tempo"
        tests:
          - unique
          - not_null

  - name: dim_localidade
    description: "Dimensão geográfica com estados e municípios"
    columns:
      - name: id_localidade
        description: "Chave primária da dimensão localidade"
        tests:
          - unique
          - not_null

  - name: fact_ocupacao_leitos
    description: "Tabela de fatos com métricas de ocupação de leitos"
    columns:
      - name: id_fato
        description: "Chave primária da tabela de fatos"
        tests:
          - unique
          - not_null