version: 2

sources:
  - name: bronze_source
    database: COVID_19
    schema: BRONZE
    tables:
      - name: RAW_LEITO_OCUPACAO_2020
      - name: RAW_LEITO_OCUPACAO_2021
      - name: RAW_LEITO_OCUPACAO_2022
      - name: RAW_MUNICIPIOS_IBGE
      - name: RAW_ESTABELECIMENTOS_CNES

models:
  - name: dim_tempo
    description: "Dimensão temporal com informações detalhadas sobre datas"
    columns:
      - name: id_tempo
        description: "Chave primária da dimensão tempo"
        tests:
          - unique
          - not_null
      - name: data
        description: "Data completa"
        tests:
          - unique
          - not_null

  - name: dim_localidade
    description: "Dimensão geográfica com estados e municípios"
    columns:
      - name: id_localidade
        description: "Chave primária da dimensão localidade"
        tests:
          - unique
          - not_null

  - name: fact_ocupacao_leitos
    description: "Tabela de fatos com métricas de ocupação de leitos"
    columns:
      - name: id_fato
        description: "Chave primária da tabela de fatos"
        tests:
          - unique
          - not_null

      - name: id_tempo
        description: "Chave estrangeira para a dimensão tempo"
        tests:
          - relationships:
              to: ref('dim_tempo')
              field: id_tempo

      - name: id_localidade
        description: "Chave estrangeira para a dimensão localidade"
        tests:
          - relationships:
              to: ref('dim_localidade')
              field: id_localidade

      - name: id_cnes
        description: "Chave estrangeira para a dimensão unidade de saúde"
        tests:
          - relationships:
              to: ref('dim_unidade_saud')
              field: id_unidade_saude

      - name: id_ocupacao_tipo
        description: "Chave estrangeira para a dimensão de tipo de ocupação"
        tests:
          - relationships:
              to: ref('dim_ocupacao_tipo')
              field: id_ocupacao_tipo

      - name: quantidade_leitos_ocupados
        description: "Número de leitos ocupados no registro"
        tests:
          - not_null

      - name: updated_at
        description: "Data da última atualização do registro"
        tests:
          - not_null