SELECT
 _id AS id_registro,
 TO_TIMESTAMP_NTZ(data_notificacao) AS data_notificacao,
 TRIM(cnes) AS cnes,
 COALESCE(ocupacao_suspeito_cli, 0) AS ocupacao_suspeito_cli,
 COALESCE(ocupacao_suspeito_uti, 0) AS ocupacao_suspeito_uti,
 COALESCE(ocupacao_confirmado_cli, 0) AS ocupacao_confirmado_cli,
 COALESCE(ocupacao_confirmado_uti, 0) AS ocupacao_confirmado_uti,
 COALESCE(ocupacao_covid_uti, 0) AS ocupacao_covid_uti,
 COALESCE(ocupacao_covid_cli, 0) AS ocupacao_covid_cli,
 COALESCE(ocupacao_hospitalar_uti, 0) AS ocupacao_hospitalar_uti,
 COALESCE(ocupacao_hospitalar_cli, 0) AS ocupacao_hospitalar_cli,
 COALESCE(saida_suspeita_obitos, 0) AS saida_suspeita_obitos,
 COALESCE(saida_suspeita_altas, 0) AS saida_suspeita_altas,
 COALESCE(saida_confirmada_obitos, 0) AS saida_confirmada_obitos,
 COALESCE(saida_confirmada_altas, 0) AS saida_confirmada_altas,
 TRIM(origem) AS origem,
 TRIM(p_usuario) AS p_usuario,
 TRIM(estado_notificacao) AS estado_notificacao,
 TRIM(municipio_notificacao) AS municipio_notificacao,
 TRIM(estado) AS estado,
 TRIM(municipio) AS municipio,
 excluido,
 validado,
 created_at,
 updated_at,
 2021 AS ano_dados
FROM {{ source('covid_2021', 'stg_leito_ocupacao_2021') }}
WHERE excluido = FALSE