version: 2

sources:
  - name: covid_2021
    database: COVID_2021
    schema: BRONZE
    tables:
      - name: stg_leito_ocupacao_2021

models:
  - name: dim_tempo
    description: "Dimensão temporal com informações detalhadas sobre datas"
    columns:
      - name: id_tempo
        description: "Chave primária da dimensão tempo"
        tests:
          - unique
          - not_null

  - name: dim_localidade
    description: "Dimensão geográfica com estados e municípios"
    columns:
      - name: id_localidade
        description: "Chave primária da dimensão localidade"
        tests:
          - unique
          - not_null

  - name: fact_ocupacao_leitos
    description: "Tabela de fatos com métricas de ocupação de leitos"
    columns:
      - name: id_fato
        description: "Chave primária da tabela de fatos"
        tests:
          - unique
          - not_null

      - name: id_tempo
        description: "Chave estrangeira para a dimensão tempo"
        tests:
          - not_null
          - relationships:
              to: ref('dim_tempo')
              field: id_tempo

      - name: id_localidade
        description: "Chave estrangeira para a dimensão localidade"
        tests:
          - not_null
          - relationships:
              to: ref('dim_localidade')
              field: id_localidade

      - name: id_unidade_saude
        description: "Chave estrangeira para a dimensão unidade de saúde"
        tests:
          - not_null
          - relationships:
              to: ref('dim_unidade_saude')
              field: id_unidade_saude

      - name: id_ocupacao_tipo
        description: "Chave estrangeira para a dimensão tipo de ocupação"
        tests:
          - not_null
          - relationships:
              to: ref('dim_ocupacao_tipo')
              field: id_ocupacao_tipo

      - name: updated_at
        description: "Timestamp de atualização do registro"
        tests:
          - not_null

  - name: dim_ocupacao_tipo
    description: "Dimensão com tipos de ocupação e tipos de leito"
    columns:
      - name: id_ocupacao_tipo
        description: "Chave primária da dimensão tipo de ocupação"
        tests:
          - unique
          - not_null
